language: node_js
node_js: stable

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

after_success:
  - cd ./dist
  - git init
  - git config --global user.name "jarbo.zhang"
  - git config --global user.email 'jarbo.zhang@gmail.com'
  - git add .
  - git commit -m 'Automatically update from travis-ci'
  - git push --quiet --force  'https://${GH_TOKEN}@${GH_REF}' master:gh-pages

env:
  global:
    - GH_REF: github.com/jarbozhang/vue-cli-zero-to-one
