language: node_js
node_js: stable

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
