language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
env:
  global:
  - secure: jdl8aXwTzmtMX0XXZQEStUu9m6LHcgG6B80MDcWdFokuNWzfhTCRYhpDFcbkwJ05k94EPuiYbcMkIxZGrc3U77ZdAl4BnWjsWZjyRZwRhNCKuSoDJ9LQUNCq95iNNO3jHkdWyRoV1mNKG0Q6kOMOKdaszZf0p3/BlTWfWAYHmVTzR8oln6a47QcdswoeOeDBJ9L5o3o7x0b9KDyIbz9onul3MGdk333PNTnU6BdikhcyJYl9ZAfmjLDDov4YYuxG1cMGakskXi+lUUotRX2osVbn3ZMmWmLM7+apJuoLkAWQ53HCbAg6541PZdcCxLMK2W6uFt7NwyOIgBe9BkA32P0LlhUnOgqGatuUp/UQuQ4sGK/eWfMa+ScUz8jtiG0pn/czeSKC262oXUYpOCGUgNyrCxaRxxuI5qCCx7Ctc9seYy9QyF0Cq8HIvoWZjAPwEZ8fhBIblhEce7WJNJx3AdH7B9Li1bwKvff4p7JT10tbNT5QARdohcFAXdDUuK3ayIdJkEN6HrjkM0z5yHlCLdjrU3092VvS2J/vl29iOkz/0Kxwk1jkCiTVfvrelJOZvuFbQV5jqYFTnEIZn1F83quso/XIiToOpnQLiCFwXLS7SAqH+Z91kn3xl59mkfCHmFBv8CGJ0ZGfg3tpTYwKaeCZof3mqXSdE007RoCVH6Y=
  - secure: tyXBlgPbgXX6ZHvu+GP9yREZ+Xl/Q0DIH9yflhxiMUancp1qTRpgmsu+A+DSWIECMURx5uNz+5ynfLvrlJLrAyHiTTVb8DRBy6aWdAs08dgNWIGU6uV6dgD2ApIC3O7ETcQ7Yg3qC/xc9UU51pLVaG7nK9k76n0zX9P3ytg2Fvs/Gt+i3VKfNcvOs9uLV50XoJcwL1wu7+M2iA/ThAdPdlHg2QTf7+0G/sqaqEhnGfPjy0qepMpRjdROmbn/biuP5hKpY2LLwXNDH1Adirz/Sp0W7QN8h1PYnZYujahKEzW/C7KxEp/j0bwd3Ht6I8y+xqVd7QfBso3cdihJ700IiW5+Jm8pGUIdj64gtsoXfDIgy+THDqSin1Kl9n+QMxDr8kPmL2Vt74F4gBHhsjZDynEGNzDfWTtTlIO7BwflN0MmlZIuJOVxB1+n4thHgqXbHRoidPHDLur/8ogDj58HkNgbQZAVNX+1au/+THtdPWnOEdGgRNnnOJapttMxEIWpH7KkSMH9W0DF2E83gE3rrsLi1vqDN0VLfZpbyWcVNapnOXPYH/VZw7vNeSuuKRT1SH0H92qtb6pG/vlRh+ssRipX+Fjwy4BFuBO+69g9Cm9IvhVy4FnquXtmPR76fFrbQE1igNm3uCzn8iXg0Wlmcf9DSMVW1pxRAd5fOk/DolM=
