branches:
  only:
    - master

language: node_js
node_js: stable

install:
  - npm install

script:
  - npm run build

after_success:
  - cd ./dist
  - cp index.html 404.html
  - git config --global user.name "jarbo.zhang"
  - git config --global user.email 'jarbo.zhang@gmail.com'
  - git add .
  - git commit -m 'Automatically update from travis-ci'
  - git push --quiet --force  'https://${GH_TOKEN}@${GH_REF}' gh-pages:gh-pages
  - git subtree push --quiet --force --prefix=dist 'https://${GH_TOKEN}@${GH_REF}' origin gh-pages

env:
  global:
    - GH_REF: github.com/jarbozhang/vue-cli-zero-to-one
    - GH_TOKEN: 3969b11f3fe448b5b27516a1d6d953f66941acea
